package com.cout970.magneticraft.gui.common

/**
 * Created by cout970 on 08/07/2016.
 */

val DATA_ID_VOLTAGE = 1
val DATA_ID_BURNING_TIME = 2
val DATA_ID_MAX_BURNING_TIME = 3
val DATA_ID_MACHINE_HEAT = 4
val DATA_ID_MACHINE_PRODUCTION = 5
val DATA_ID_FLUID_AMOUNT = 6
val DATA_ID_FLUID_NAME = 7
val DATA_ID_STORAGE = 8
val DATA_ID_CHARGE_RATE = 9
val DATA_ID_MACHINE_WORKING = 10
val DATA_ID_ITEM_CHARGE_RATE = 11
val DATA_ID_MAX_FREEZING_TIME = 12
val DATA_ID_FREEZING_TIME = 13