package com.cout970.magneticraft.gui.common.core

/**
 * Created by cout970 on 08/07/2016.
 */

val DATA_ID_VOLTAGE_0 = 1
val DATA_ID_BURNING_TIME = 2 // used in furnaces and generators, don't mix
val DATA_ID_MAX_BURNING_TIME = 3
val DATA_ID_MACHINE_HEAT = 4
val DATA_ID_MACHINE_PRODUCTION = 5
val DATA_ID_FLUID_AMOUNT = 6
val DATA_ID_FLUID_NAME = 7
val DATA_ID_STORAGE = 8
val DATA_ID_CHARGE_RATE = 9
val DATA_ID_MACHINE_WORKING = 10
val DATA_ID_ITEM_CHARGE_RATE = 11
val DATA_ID_MAX_FREEZING_TIME = 12
val DATA_ID_FREEZING_TIME = 13
val DATA_ID_VOLTAGE_1 = 14
val DATA_ID_VOLTAGE_2 = 15
val DATA_ID_VOLTAGE_3 = 16
val DATA_ID_MONITOR_CURSOR_LINE = 17
val DATA_ID_MONITOR_CURSOR_COLUMN = 18
val DATA_ID_MONITOR_BUFFER = 19
val DATA_ID_MONITOR_HAS_KEY = 20
val DATA_ID_MONITOR_KEY = 20
val DATA_ID_MONITOR_MOUSE_CLICK = 21
val DATA_ID_MONITOR_MOUSE_BUTTON = 22
val DATA_ID_MONITOR_MOUSE_X = 23
val DATA_ID_MONITOR_MOUSE_Y = 24
val DATA_ID_COMPUTER_BUTTON = 25
val DATA_ID_COMPUTER_LIGHT = 26
val DATA_ID_SHELVING_UNIT_SCROLL = 27
val DATA_ID_SHELVING_UNIT_FILTER = 28
val DATA_ID_SHELVING_UNIT_LEVEL = 29
val DATA_ID_THERMOPILE_SOURCE = 30
val DATA_ID_THERMOPILE_DRAIN = 31
val DATA_ID_THERMOPILE_PRODUCTION = 32

val DATA_ID_VOLTAGE_LIST = listOf(
        DATA_ID_VOLTAGE_0,
        DATA_ID_VOLTAGE_1,
        DATA_ID_VOLTAGE_2,
        DATA_ID_VOLTAGE_3
)