// Date: 11/01/2016 17:13:27
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelWindTurbine extends ModelBase {
    //fields
    ModelRenderer axix;
    ModelRenderer pole;
    ModelRenderer wool;
    ModelRenderer pole2;
    ModelRenderer pole3;
    ModelRenderer pole4;
    ModelRenderer wool2;
    ModelRenderer wool3;
    ModelRenderer wool4;

    public ModelWindTurbine() {
        textureWidth = 64;
        textureHeight = 64;

        axix = new ModelRenderer(this, 0, 0);
        axix.addBox(-2F, -2F, -2F, 4, 10, 4);
        axix.setRotationPoint(0F, 16F, 0F);
        axix.setTextureSize(64, 64);
        axix.mirror = true;
        setRotation(axix, 0F, 0F, 0F);
        pole = new ModelRenderer(this, 0, 0);
        pole.addBox(-1F, 0F, 2F, 2, 2, 22);
        pole.setRotationPoint(0F, 16F, 0F);
        pole.setTextureSize(64, 64);
        pole.mirror = true;
        setRotation(pole, 0F, 0F, 0F);
        wool = new ModelRenderer(this, 0, 24);
        wool.addBox(0F, 0.5F, 7F, 7, 1, 16);
        wool.setRotationPoint(0F, 16F, 0F);
        wool.setTextureSize(64, 64);
        wool.mirror = true;
        setRotation(wool, 0F, 0F, 0.2617994F);
        pole2 = new ModelRenderer(this, 0, 0);
        pole2.addBox(-1F, 0F, -24F, 2, 2, 22);
        pole2.setRotationPoint(0F, 16F, 0F);
        pole2.setTextureSize(64, 64);
        pole2.mirror = true;
        setRotation(pole2, 0F, 0F, 0F);
        pole3 = new ModelRenderer(this, 0, 41);
        pole3.addBox(2F, 0F, -1F, 22, 2, 2);
        pole3.setRotationPoint(0F, 16F, 0F);
        pole3.setTextureSize(64, 64);
        pole3.mirror = true;
        setRotation(pole3, 0F, 0F, 0F);
        pole4 = new ModelRenderer(this, 0, 41);
        pole4.addBox(-24F, 0F, 0F, 22, 2, 2);
        pole4.setRotationPoint(0F, 16F, -1F);
        pole4.setTextureSize(64, 64);
        pole4.mirror = true;
        setRotation(pole4, 0F, 0F, 0F);
        wool2 = new ModelRenderer(this, 0, 24);
        wool2.addBox(-7F, 0F, -23F, 7, 1, 16);
        wool2.setRotationPoint(0F, 16F, 0F);
        wool2.setTextureSize(64, 64);
        wool2.mirror = true;
        setRotation(wool2, 0F, 0F, -0.2617994F);
        wool3 = new ModelRenderer(this, 0, 45);
        wool3.addBox(7F, 0F, -7F, 16, 1, 7);
        wool3.setRotationPoint(0F, 16F, 0F);
        wool3.setTextureSize(64, 64);
        wool3.mirror = true;
        setRotation(wool3, 0.2617994F, 0F, 0F);
        wool4 = new ModelRenderer(this, 0, 45);
        wool4.addBox(-23F, 0F, 0F, 16, 1, 7);
        wool4.setRotationPoint(0F, 16F, 0F);
        wool4.setTextureSize(64, 64);
        wool4.mirror = true;
        setRotation(wool4, -0.2617994F, 0F, 0F);
    }

//  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
//  {
//    super.render(entity, f, f1, f2, f3, f4, f5);
//    setRotationAngles(f, f1, f2, f3, f4, f5);
//    axix.render(f5);
//    pole.render(f5);
//    wool.render(f5);
//    pole2.render(f5);
//    pole3.render(f5);
//    pole4.render(f5);
//    wool2.render(f5);
//    wool3.render(f5);
//    wool4.render(f5);
//  }

    public void renderStatic(float f5) {
        axix.render(f5);
        pole.render(f5);
        wool.render(f5);
        pole2.render(f5);
        pole3.render(f5);
        pole4.render(f5);
        wool2.render(f5);
        wool3.render(f5);
        wool4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

//  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
//  {
//    super.setRotationAngles(f, f1, f2, f3, f4, f5);
//  }

}
